namespace IceFlake.Client.Patchables
{

    public enum WoWObjectFields
    {
        OBJECT_FIELD_GUID = 0x0000, // Size: 2, Type: LONG, Flags: PUBLIC
        OBJECT_FIELD_TYPE = 0x0002, // Size: 1, Type: INT, Flags: PUBLIC
        OBJECT_FIELD_ENTRY = 0x0003, // Size: 1, Type: INT, Flags: PUBLIC
        OBJECT_FIELD_SCALE_X = 0x0004, // Size: 1, Type: FLOAT, Flags: PUBLIC
        OBJECT_FIELD_PADDING = 0x0005, // Size: 1, Type: INT, Flags: NONE
        OBJECT_END = 0x0006,
    };

    public enum WoWItemFields
    {
        ITEM_FIELD_OWNER = WoWObjectFields.OBJECT_END + 0x0000, // Size: 2, Type: LONG, Flags: PUBLIC
        ITEM_FIELD_CONTAINED = WoWObjectFields.OBJECT_END + 0x0002, // Size: 2, Type: LONG, Flags: PUBLIC
        ITEM_FIELD_CREATOR = WoWObjectFields.OBJECT_END + 0x0004, // Size: 2, Type: LONG, Flags: PUBLIC
        ITEM_FIELD_GIFTCREATOR = WoWObjectFields.OBJECT_END + 0x0006, // Size: 2, Type: LONG, Flags: PUBLIC
        ITEM_FIELD_STACK_COUNT = WoWObjectFields.OBJECT_END + 0x0008, // Size: 1, Type: INT, Flags: OWNER, ITEM_OWNER
        ITEM_FIELD_DURATION = WoWObjectFields.OBJECT_END + 0x0009, // Size: 1, Type: INT, Flags: OWNER, ITEM_OWNER
        ITEM_FIELD_SPELL_CHARGES = WoWObjectFields.OBJECT_END + 0x000A, // Size: 5, Type: INT, Flags: OWNER, ITEM_OWNER
        ITEM_FIELD_FLAGS = WoWObjectFields.OBJECT_END + 0x000F, // Size: 1, Type: INT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_1_1 = WoWObjectFields.OBJECT_END + 0x0010, // Size: 2, Type: INT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_1_3 = WoWObjectFields.OBJECT_END + 0x0012, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_2_1 = WoWObjectFields.OBJECT_END + 0x0013, // Size: 2, Type: INT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_2_3 = WoWObjectFields.OBJECT_END + 0x0015, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_3_1 = WoWObjectFields.OBJECT_END + 0x0016, // Size: 2, Type: INT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_3_3 = WoWObjectFields.OBJECT_END + 0x0018, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_4_1 = WoWObjectFields.OBJECT_END + 0x0019, // Size: 2, Type: INT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_4_3 = WoWObjectFields.OBJECT_END + 0x001B, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_5_1 = WoWObjectFields.OBJECT_END + 0x001C, // Size: 2, Type: INT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_5_3 = WoWObjectFields.OBJECT_END + 0x001E, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_6_1 = WoWObjectFields.OBJECT_END + 0x001F, // Size: 2, Type: INT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_6_3 = WoWObjectFields.OBJECT_END + 0x0021, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_7_1 = WoWObjectFields.OBJECT_END + 0x0022, // Size: 2, Type: INT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_7_3 = WoWObjectFields.OBJECT_END + 0x0024, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_8_1 = WoWObjectFields.OBJECT_END + 0x0025, // Size: 2, Type: INT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_8_3 = WoWObjectFields.OBJECT_END + 0x0027, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_9_1 = WoWObjectFields.OBJECT_END + 0x0028, // Size: 2, Type: INT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_9_3 = WoWObjectFields.OBJECT_END + 0x002A, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_10_1 = WoWObjectFields.OBJECT_END + 0x002B, // Size: 2, Type: INT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_10_3 = WoWObjectFields.OBJECT_END + 0x002D, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_11_1 = WoWObjectFields.OBJECT_END + 0x002E, // Size: 2, Type: INT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_11_3 = WoWObjectFields.OBJECT_END + 0x0030, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_12_1 = WoWObjectFields.OBJECT_END + 0x0031, // Size: 2, Type: INT, Flags: PUBLIC
        ITEM_FIELD_ENCHANTMENT_12_3 = WoWObjectFields.OBJECT_END + 0x0033, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        ITEM_FIELD_PROPERTY_SEED = WoWObjectFields.OBJECT_END + 0x0034, // Size: 1, Type: INT, Flags: PUBLIC
        ITEM_FIELD_RANDOM_PROPERTIES_ID = WoWObjectFields.OBJECT_END + 0x0035, // Size: 1, Type: INT, Flags: PUBLIC
        ITEM_FIELD_DURABILITY = WoWObjectFields.OBJECT_END + 0x0036, // Size: 1, Type: INT, Flags: OWNER, ITEM_OWNER
        ITEM_FIELD_MAXDURABILITY = WoWObjectFields.OBJECT_END + 0x0037, // Size: 1, Type: INT, Flags: OWNER, ITEM_OWNER
        ITEM_FIELD_CREATE_PLAYED_TIME = WoWObjectFields.OBJECT_END + 0x0038, // Size: 1, Type: INT, Flags: PUBLIC
        ITEM_FIELD_PAD = WoWObjectFields.OBJECT_END + 0x0039, // Size: 1, Type: INT, Flags: NONE
        ITEM_END = WoWObjectFields.OBJECT_END + 0x003A,
    };

    public enum WoWContainerFields
    {
        CONTAINER_FIELD_NUM_SLOTS = WoWItemFields.ITEM_END + 0x0000, // Size: 1, Type: INT, Flags: PUBLIC
        CONTAINER_ALIGN_PAD = WoWItemFields.ITEM_END + 0x0001, // Size: 1, Type: BYTES, Flags: NONE
        CONTAINER_FIELD_SLOT_1 = WoWItemFields.ITEM_END + 0x0002, // Size: 72, Type: LONG, Flags: PUBLIC
        CONTAINER_END = WoWItemFields.ITEM_END + 0x004A,
    };

    public enum WoWUnitFields
    {
        UNIT_FIELD_CHARM = WoWObjectFields.OBJECT_END + 0x0000, // Size: 2, Type: LONG, Flags: PUBLIC
        UNIT_FIELD_SUMMON = WoWObjectFields.OBJECT_END + 0x0002, // Size: 2, Type: LONG, Flags: PUBLIC
        UNIT_FIELD_CRITTER = WoWObjectFields.OBJECT_END + 0x0004, // Size: 2, Type: LONG, Flags: PRIVATE
        UNIT_FIELD_CHARMEDBY = WoWObjectFields.OBJECT_END + 0x0006, // Size: 2, Type: LONG, Flags: PUBLIC
        UNIT_FIELD_SUMMONEDBY = WoWObjectFields.OBJECT_END + 0x0008, // Size: 2, Type: LONG, Flags: PUBLIC
        UNIT_FIELD_CREATEDBY = WoWObjectFields.OBJECT_END + 0x000A, // Size: 2, Type: LONG, Flags: PUBLIC
        UNIT_FIELD_TARGET = WoWObjectFields.OBJECT_END + 0x000C, // Size: 2, Type: LONG, Flags: PUBLIC
        UNIT_FIELD_CHANNEL_OBJECT = WoWObjectFields.OBJECT_END + 0x000E, // Size: 2, Type: LONG, Flags: PUBLIC
        UNIT_CHANNEL_SPELL = WoWObjectFields.OBJECT_END + 0x0010, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_BYTES_0 = WoWObjectFields.OBJECT_END + 0x0011, // Size: 1, Type: BYTES, Flags: PUBLIC
        UNIT_FIELD_HEALTH = WoWObjectFields.OBJECT_END + 0x0012, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_POWER1 = WoWObjectFields.OBJECT_END + 0x0013, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_POWER2 = WoWObjectFields.OBJECT_END + 0x0014, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_POWER3 = WoWObjectFields.OBJECT_END + 0x0015, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_POWER4 = WoWObjectFields.OBJECT_END + 0x0016, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_POWER5 = WoWObjectFields.OBJECT_END + 0x0017, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_POWER6 = WoWObjectFields.OBJECT_END + 0x0018, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_POWER7 = WoWObjectFields.OBJECT_END + 0x0019, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_MAXHEALTH = WoWObjectFields.OBJECT_END + 0x001A, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_MAXPOWER1 = WoWObjectFields.OBJECT_END + 0x001B, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_MAXPOWER2 = WoWObjectFields.OBJECT_END + 0x001C, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_MAXPOWER3 = WoWObjectFields.OBJECT_END + 0x001D, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_MAXPOWER4 = WoWObjectFields.OBJECT_END + 0x001E, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_MAXPOWER5 = WoWObjectFields.OBJECT_END + 0x001F, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_MAXPOWER6 = WoWObjectFields.OBJECT_END + 0x0020, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_MAXPOWER7 = WoWObjectFields.OBJECT_END + 0x0021, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER = WoWObjectFields.OBJECT_END + 0x0022, // Size: 7, Type: FLOAT, Flags: PRIVATE, OWNER
        UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER = WoWObjectFields.OBJECT_END + 0x0029, // Size: 7, Type: FLOAT, Flags: PRIVATE, OWNER
        UNIT_FIELD_LEVEL = WoWObjectFields.OBJECT_END + 0x0030, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_FACTIONTEMPLATE = WoWObjectFields.OBJECT_END + 0x0031, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_VIRTUAL_ITEM_SLOT_ID = WoWObjectFields.OBJECT_END + 0x0032, // Size: 3, Type: INT, Flags: PUBLIC
        UNIT_FIELD_FLAGS = WoWObjectFields.OBJECT_END + 0x0035, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_FLAGS_2 = WoWObjectFields.OBJECT_END + 0x0036, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_AURASTATE = WoWObjectFields.OBJECT_END + 0x0037, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_BASEATTACKTIME = WoWObjectFields.OBJECT_END + 0x0038, // Size: 2, Type: INT, Flags: PUBLIC
        UNIT_FIELD_RANGEDATTACKTIME = WoWObjectFields.OBJECT_END + 0x003A, // Size: 1, Type: INT, Flags: PRIVATE
        UNIT_FIELD_BOUNDINGRADIUS = WoWObjectFields.OBJECT_END + 0x003B, // Size: 1, Type: FLOAT, Flags: PUBLIC
        UNIT_FIELD_COMBATREACH = WoWObjectFields.OBJECT_END + 0x003C, // Size: 1, Type: FLOAT, Flags: PUBLIC
        UNIT_FIELD_DISPLAYID = WoWObjectFields.OBJECT_END + 0x003D, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_NATIVEDISPLAYID = WoWObjectFields.OBJECT_END + 0x003E, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_MOUNTDISPLAYID = WoWObjectFields.OBJECT_END + 0x003F, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_MINDAMAGE = WoWObjectFields.OBJECT_END + 0x0040, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER, PARTY_LEADER
        UNIT_FIELD_MAXDAMAGE = WoWObjectFields.OBJECT_END + 0x0041, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER, PARTY_LEADER
        UNIT_FIELD_MINOFFHANDDAMAGE = WoWObjectFields.OBJECT_END + 0x0042, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER, PARTY_LEADER
        UNIT_FIELD_MAXOFFHANDDAMAGE = WoWObjectFields.OBJECT_END + 0x0043, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER, PARTY_LEADER
        UNIT_FIELD_BYTES_1 = WoWObjectFields.OBJECT_END + 0x0044, // Size: 1, Type: BYTES, Flags: PUBLIC
        UNIT_FIELD_PETNUMBER = WoWObjectFields.OBJECT_END + 0x0045, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_PET_NAME_TIMESTAMP = WoWObjectFields.OBJECT_END + 0x0046, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_PETEXPERIENCE = WoWObjectFields.OBJECT_END + 0x0047, // Size: 1, Type: INT, Flags: OWNER
        UNIT_FIELD_PETNEXTLEVELEXP = WoWObjectFields.OBJECT_END + 0x0048, // Size: 1, Type: INT, Flags: OWNER
        UNIT_DYNAMIC_FLAGS = WoWObjectFields.OBJECT_END + 0x0049, // Size: 1, Type: INT, Flags: DYNAMIC
        UNIT_MOD_CAST_SPEED = WoWObjectFields.OBJECT_END + 0x004A, // Size: 1, Type: FLOAT, Flags: PUBLIC
        UNIT_CREATED_BY_SPELL = WoWObjectFields.OBJECT_END + 0x004B, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_NPC_FLAGS = WoWObjectFields.OBJECT_END + 0x004C, // Size: 1, Type: INT, Flags: DYNAMIC
        UNIT_NPC_EMOTESTATE = WoWObjectFields.OBJECT_END + 0x004D, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_STAT0 = WoWObjectFields.OBJECT_END + 0x004E, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_STAT1 = WoWObjectFields.OBJECT_END + 0x004F, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_STAT2 = WoWObjectFields.OBJECT_END + 0x0050, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_STAT3 = WoWObjectFields.OBJECT_END + 0x0051, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_STAT4 = WoWObjectFields.OBJECT_END + 0x0052, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_POSSTAT0 = WoWObjectFields.OBJECT_END + 0x0053, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_POSSTAT1 = WoWObjectFields.OBJECT_END + 0x0054, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_POSSTAT2 = WoWObjectFields.OBJECT_END + 0x0055, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_POSSTAT3 = WoWObjectFields.OBJECT_END + 0x0056, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_POSSTAT4 = WoWObjectFields.OBJECT_END + 0x0057, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_NEGSTAT0 = WoWObjectFields.OBJECT_END + 0x0058, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_NEGSTAT1 = WoWObjectFields.OBJECT_END + 0x0059, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_NEGSTAT2 = WoWObjectFields.OBJECT_END + 0x005A, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_NEGSTAT3 = WoWObjectFields.OBJECT_END + 0x005B, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_NEGSTAT4 = WoWObjectFields.OBJECT_END + 0x005C, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_RESISTANCES = WoWObjectFields.OBJECT_END + 0x005D, // Size: 7, Type: INT, Flags: PRIVATE, OWNER, PARTY_LEADER
        UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE = WoWObjectFields.OBJECT_END + 0x0064, // Size: 7, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE = WoWObjectFields.OBJECT_END + 0x006B, // Size: 7, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_BASE_MANA = WoWObjectFields.OBJECT_END + 0x0072, // Size: 1, Type: INT, Flags: PUBLIC
        UNIT_FIELD_BASE_HEALTH = WoWObjectFields.OBJECT_END + 0x0073, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_BYTES_2 = WoWObjectFields.OBJECT_END + 0x0074, // Size: 1, Type: BYTES, Flags: PUBLIC
        UNIT_FIELD_ATTACK_POWER = WoWObjectFields.OBJECT_END + 0x0075, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_ATTACK_POWER_MODS = WoWObjectFields.OBJECT_END + 0x0076, // Size: 1, Type: TWO_SHORT, Flags: PRIVATE, OWNER
        UNIT_FIELD_ATTACK_POWER_MULTIPLIER = WoWObjectFields.OBJECT_END + 0x0077, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
        UNIT_FIELD_RANGED_ATTACK_POWER = WoWObjectFields.OBJECT_END + 0x0078, // Size: 1, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_RANGED_ATTACK_POWER_MODS = WoWObjectFields.OBJECT_END + 0x0079, // Size: 1, Type: TWO_SHORT, Flags: PRIVATE, OWNER
        UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER = WoWObjectFields.OBJECT_END + 0x007A, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
        UNIT_FIELD_MINRANGEDDAMAGE = WoWObjectFields.OBJECT_END + 0x007B, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
        UNIT_FIELD_MAXRANGEDDAMAGE = WoWObjectFields.OBJECT_END + 0x007C, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
        UNIT_FIELD_POWER_COST_MODIFIER = WoWObjectFields.OBJECT_END + 0x007D, // Size: 7, Type: INT, Flags: PRIVATE, OWNER
        UNIT_FIELD_POWER_COST_MULTIPLIER = WoWObjectFields.OBJECT_END + 0x0084, // Size: 7, Type: FLOAT, Flags: PRIVATE, OWNER
        UNIT_FIELD_MAXHEALTHMODIFIER = WoWObjectFields.OBJECT_END + 0x008B, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
        UNIT_FIELD_HOVERHEIGHT = WoWObjectFields.OBJECT_END + 0x008C, // Size: 1, Type: FLOAT, Flags: PUBLIC
        UNIT_FIELD_PADDING = WoWObjectFields.OBJECT_END + 0x008D, // Size: 1, Type: INT, Flags: NONE
        UNIT_END = WoWObjectFields.OBJECT_END + 0x008E,

        /*/
        UNIT_CHANNEL_SPELL = 0x16,
        UNIT_CREATED_BY_SPELL = 0x51,
        UNIT_DYNAMIC_FLAGS = 0x4f,
        UNIT_FIELD_ATTACK_POWER = 0x7b,
        UNIT_FIELD_ATTACK_POWER_MODS = 0x7c,
        UNIT_FIELD_ATTACK_POWER_MULTIPLIER = 0x7d,
        UNIT_FIELD_AURASTATE = 0x3d,
        UNIT_FIELD_BASE_HEALTH = 0x79,
        UNIT_FIELD_BASE_MANA = 120,
        UNIT_FIELD_BASEATTACKTIME = 0x3e,
        UNIT_FIELD_BOUNDINGRADIUS = 0x41,
        UNIT_FIELD_BYTES_0 = 0x17,
        UNIT_FIELD_BYTES_1 = 0x4a,
        UNIT_FIELD_BYTES_2 = 0x7a,
        UNIT_FIELD_CHANNEL_OBJECT = 20,
        UNIT_FIELD_CHARM = 6,
        UNIT_FIELD_CHARMEDBY = 12,
        UNIT_FIELD_COMBATREACH = 0x42,
        UNIT_FIELD_CREATEDBY = 0x10,
        UNIT_FIELD_CRITTER = 10,
        UNIT_FIELD_DISPLAYID = 0x43,
        UNIT_FIELD_FACTIONTEMPLATE = 0x37,
        UNIT_FIELD_FLAGS = 0x3b,
        UNIT_FIELD_FLAGS_2 = 60,
        UNIT_FIELD_HEALTH = 0x18,
        UNIT_FIELD_HOVERHEIGHT = 0x92,
        UNIT_FIELD_LEVEL = 0x36,
        UNIT_FIELD_MAXDAMAGE = 0x47,
        UNIT_FIELD_MAXHEALTH = 0x20,
        UNIT_FIELD_MAXHEALTHMODIFIER = 0x91,
        UNIT_FIELD_MAXOFFHANDDAMAGE = 0x49,
        UNIT_FIELD_MAXPOWER1 = 0x21,
        UNIT_FIELD_MAXPOWER2 = 0x22,
        UNIT_FIELD_MAXPOWER3 = 0x23,
        UNIT_FIELD_MAXPOWER4 = 0x24,
        UNIT_FIELD_MAXPOWER5 = 0x25,
        UNIT_FIELD_MAXPOWER6 = 0x26,
        UNIT_FIELD_MAXPOWER7 = 0x27,
        UNIT_FIELD_MAXRANGEDDAMAGE = 130,
        UNIT_FIELD_MINDAMAGE = 70,
        UNIT_FIELD_MINOFFHANDDAMAGE = 0x48,
        UNIT_FIELD_MINRANGEDDAMAGE = 0x81,
        UNIT_FIELD_MOUNTDISPLAYID = 0x45,
        UNIT_FIELD_NATIVEDISPLAYID = 0x44,
        UNIT_FIELD_NEGSTAT0 = 0x5e,
        UNIT_FIELD_NEGSTAT1 = 0x5f,
        UNIT_FIELD_NEGSTAT2 = 0x60,
        UNIT_FIELD_NEGSTAT3 = 0x61,
        UNIT_FIELD_NEGSTAT4 = 0x62,
        UNIT_FIELD_PADDING = 0x93,
        UNIT_FIELD_PET_NAME_TIMESTAMP = 0x4c,
        UNIT_FIELD_PETEXPERIENCE = 0x4d,
        UNIT_FIELD_PETNEXTLEVELEXP = 0x4e,
        UNIT_FIELD_PETNUMBER = 0x4b,
        UNIT_FIELD_POSSTAT0 = 0x59,
        UNIT_FIELD_POSSTAT1 = 90,
        UNIT_FIELD_POSSTAT2 = 0x5b,
        UNIT_FIELD_POSSTAT3 = 0x5c,
        UNIT_FIELD_POSSTAT4 = 0x5d,
        UNIT_FIELD_POWER_COST_MODIFIER = 0x83,
        UNIT_FIELD_POWER_COST_MULTIPLIER = 0x8a,
        UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER = 40,
        UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER = 0x2f,
        UNIT_FIELD_POWER1 = 0x19,
        UNIT_FIELD_POWER2 = 0x1a,
        UNIT_FIELD_POWER3 = 0x1b,
        UNIT_FIELD_POWER4 = 0x1c,
        UNIT_FIELD_POWER5 = 0x1d,
        UNIT_FIELD_POWER6 = 30,
        UNIT_FIELD_POWER7 = 0x1f,
        UNIT_FIELD_RANGED_ATTACK_POWER = 0x7e,
        UNIT_FIELD_RANGED_ATTACK_POWER_MODS = 0x7f,
        UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER = 0x80,
        UNIT_FIELD_RANGEDATTACKTIME = 0x40,
        UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE = 0x71,
        UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE = 0x6a,
        UNIT_FIELD_RESISTANCES = 0x63,
        UNIT_FIELD_STAT0 = 0x54,
        UNIT_FIELD_STAT1 = 0x55,
        UNIT_FIELD_STAT2 = 0x56,
        UNIT_FIELD_STAT3 = 0x57,
        UNIT_FIELD_STAT4 = 0x58,
        UNIT_FIELD_SUMMON = 8,
        UNIT_FIELD_SUMMONEDBY = 14,
        UNIT_FIELD_TARGET = 0x12,
        UNIT_MOD_CAST_SPEED = 80,
        UNIT_NPC_EMOTESTATE = 0x53,
        UNIT_NPC_FLAGS = 0x52,
        UNIT_VIRTUAL_ITEM_SLOT_ID = 0x38,

        UNIT_END = WoWObjectFields.OBJECT_END + 0x008E,
        /*/
    };

    public enum WoWPlayerFields
    {
        PLAYER_DUEL_ARBITER = WoWUnitFields.UNIT_END + 0x0000, // Size: 2, Type: LONG, Flags: PUBLIC
        PLAYER_FLAGS = WoWUnitFields.UNIT_END + 0x0002, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_GUILDID = WoWUnitFields.UNIT_END + 0x0003, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_GUILDRANK = WoWUnitFields.UNIT_END + 0x0004, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_BYTES = WoWUnitFields.UNIT_END + 0x0005, // Size: 1, Type: BYTES, Flags: PUBLIC
        PLAYER_BYTES_2 = WoWUnitFields.UNIT_END + 0x0006, // Size: 1, Type: BYTES, Flags: PUBLIC
        PLAYER_BYTES_3 = WoWUnitFields.UNIT_END + 0x0007, // Size: 1, Type: BYTES, Flags: PUBLIC
        PLAYER_DUEL_TEAM = WoWUnitFields.UNIT_END + 0x0008, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_GUILD_TIMESTAMP = WoWUnitFields.UNIT_END + 0x0009, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_QUEST_LOG_1_1 = WoWUnitFields.UNIT_END + 0x000A, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_1_2 = WoWUnitFields.UNIT_END + 0x000B, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_1_3 = WoWUnitFields.UNIT_END + 0x000C, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_1_4 = WoWUnitFields.UNIT_END + 0x000E, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_2_1 = WoWUnitFields.UNIT_END + 0x000F, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_2_2 = WoWUnitFields.UNIT_END + 0x0010, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_2_3 = WoWUnitFields.UNIT_END + 0x0011, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_2_5 = WoWUnitFields.UNIT_END + 0x0013, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_3_1 = WoWUnitFields.UNIT_END + 0x0014, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_3_2 = WoWUnitFields.UNIT_END + 0x0015, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_3_3 = WoWUnitFields.UNIT_END + 0x0016, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_3_5 = WoWUnitFields.UNIT_END + 0x0018, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_4_1 = WoWUnitFields.UNIT_END + 0x0019, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_4_2 = WoWUnitFields.UNIT_END + 0x001A, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_4_3 = WoWUnitFields.UNIT_END + 0x001B, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_4_5 = WoWUnitFields.UNIT_END + 0x001D, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_5_1 = WoWUnitFields.UNIT_END + 0x001E, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_5_2 = WoWUnitFields.UNIT_END + 0x001F, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_5_3 = WoWUnitFields.UNIT_END + 0x0020, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_5_5 = WoWUnitFields.UNIT_END + 0x0022, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_6_1 = WoWUnitFields.UNIT_END + 0x0023, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_6_2 = WoWUnitFields.UNIT_END + 0x0024, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_6_3 = WoWUnitFields.UNIT_END + 0x0025, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_6_5 = WoWUnitFields.UNIT_END + 0x0027, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_7_1 = WoWUnitFields.UNIT_END + 0x0028, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_7_2 = WoWUnitFields.UNIT_END + 0x0029, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_7_3 = WoWUnitFields.UNIT_END + 0x002A, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_7_5 = WoWUnitFields.UNIT_END + 0x002C, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_8_1 = WoWUnitFields.UNIT_END + 0x002D, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_8_2 = WoWUnitFields.UNIT_END + 0x002E, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_8_3 = WoWUnitFields.UNIT_END + 0x002F, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_8_5 = WoWUnitFields.UNIT_END + 0x0031, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_9_1 = WoWUnitFields.UNIT_END + 0x0032, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_9_2 = WoWUnitFields.UNIT_END + 0x0033, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_9_3 = WoWUnitFields.UNIT_END + 0x0034, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_9_5 = WoWUnitFields.UNIT_END + 0x0036, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_10_1 = WoWUnitFields.UNIT_END + 0x0037, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_10_2 = WoWUnitFields.UNIT_END + 0x0038, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_10_3 = WoWUnitFields.UNIT_END + 0x0039, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_10_5 = WoWUnitFields.UNIT_END + 0x003B, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_11_1 = WoWUnitFields.UNIT_END + 0x003C, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_11_2 = WoWUnitFields.UNIT_END + 0x003D, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_11_3 = WoWUnitFields.UNIT_END + 0x003E, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_11_5 = WoWUnitFields.UNIT_END + 0x0040, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_12_1 = WoWUnitFields.UNIT_END + 0x0041, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_12_2 = WoWUnitFields.UNIT_END + 0x0042, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_12_3 = WoWUnitFields.UNIT_END + 0x0043, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_12_5 = WoWUnitFields.UNIT_END + 0x0045, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_13_1 = WoWUnitFields.UNIT_END + 0x0046, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_13_2 = WoWUnitFields.UNIT_END + 0x0047, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_13_3 = WoWUnitFields.UNIT_END + 0x0048, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_13_5 = WoWUnitFields.UNIT_END + 0x004A, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_14_1 = WoWUnitFields.UNIT_END + 0x004B, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_14_2 = WoWUnitFields.UNIT_END + 0x004C, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_14_3 = WoWUnitFields.UNIT_END + 0x004D, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_14_5 = WoWUnitFields.UNIT_END + 0x004F, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_15_1 = WoWUnitFields.UNIT_END + 0x0050, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_15_2 = WoWUnitFields.UNIT_END + 0x0051, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_15_3 = WoWUnitFields.UNIT_END + 0x0052, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_15_5 = WoWUnitFields.UNIT_END + 0x0054, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_16_1 = WoWUnitFields.UNIT_END + 0x0055, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_16_2 = WoWUnitFields.UNIT_END + 0x0056, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_16_3 = WoWUnitFields.UNIT_END + 0x0057, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_16_5 = WoWUnitFields.UNIT_END + 0x0059, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_17_1 = WoWUnitFields.UNIT_END + 0x005A, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_17_2 = WoWUnitFields.UNIT_END + 0x005B, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_17_3 = WoWUnitFields.UNIT_END + 0x005C, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_17_5 = WoWUnitFields.UNIT_END + 0x005E, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_18_1 = WoWUnitFields.UNIT_END + 0x005F, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_18_2 = WoWUnitFields.UNIT_END + 0x0060, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_18_3 = WoWUnitFields.UNIT_END + 0x0061, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_18_5 = WoWUnitFields.UNIT_END + 0x0063, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_19_1 = WoWUnitFields.UNIT_END + 0x0064, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_19_2 = WoWUnitFields.UNIT_END + 0x0065, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_19_3 = WoWUnitFields.UNIT_END + 0x0066, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_19_5 = WoWUnitFields.UNIT_END + 0x0068, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_20_1 = WoWUnitFields.UNIT_END + 0x0069, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_20_2 = WoWUnitFields.UNIT_END + 0x006A, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_20_3 = WoWUnitFields.UNIT_END + 0x006B, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_20_5 = WoWUnitFields.UNIT_END + 0x006D, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_21_1 = WoWUnitFields.UNIT_END + 0x006E, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_21_2 = WoWUnitFields.UNIT_END + 0x006F, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_21_3 = WoWUnitFields.UNIT_END + 0x0070, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_21_5 = WoWUnitFields.UNIT_END + 0x0072, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_22_1 = WoWUnitFields.UNIT_END + 0x0073, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_22_2 = WoWUnitFields.UNIT_END + 0x0074, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_22_3 = WoWUnitFields.UNIT_END + 0x0075, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_22_5 = WoWUnitFields.UNIT_END + 0x0077, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_23_1 = WoWUnitFields.UNIT_END + 0x0078, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_23_2 = WoWUnitFields.UNIT_END + 0x0079, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_23_3 = WoWUnitFields.UNIT_END + 0x007A, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_23_5 = WoWUnitFields.UNIT_END + 0x007C, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_24_1 = WoWUnitFields.UNIT_END + 0x007D, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_24_2 = WoWUnitFields.UNIT_END + 0x007E, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_24_3 = WoWUnitFields.UNIT_END + 0x007F, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_24_5 = WoWUnitFields.UNIT_END + 0x0081, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_25_1 = WoWUnitFields.UNIT_END + 0x0082, // Size: 1, Type: INT, Flags: PARTY_MEMBER
        PLAYER_QUEST_LOG_25_2 = WoWUnitFields.UNIT_END + 0x0083, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_QUEST_LOG_25_3 = WoWUnitFields.UNIT_END + 0x0084, // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_QUEST_LOG_25_5 = WoWUnitFields.UNIT_END + 0x0086, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_VISIBLE_ITEM_1_ENTRYID = WoWUnitFields.UNIT_END + 0x0087, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_1_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x0088, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_2_ENTRYID = WoWUnitFields.UNIT_END + 0x0089, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_2_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x008A, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_3_ENTRYID = WoWUnitFields.UNIT_END + 0x008B, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_3_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x008C, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_4_ENTRYID = WoWUnitFields.UNIT_END + 0x008D, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_4_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x008E, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_5_ENTRYID = WoWUnitFields.UNIT_END + 0x008F, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_5_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x0090, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_6_ENTRYID = WoWUnitFields.UNIT_END + 0x0091, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_6_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x0092, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_7_ENTRYID = WoWUnitFields.UNIT_END + 0x0093, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_7_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x0094, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_8_ENTRYID = WoWUnitFields.UNIT_END + 0x0095, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_8_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x0096, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_9_ENTRYID = WoWUnitFields.UNIT_END + 0x0097, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_9_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x0098, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_10_ENTRYID = WoWUnitFields.UNIT_END + 0x0099, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_10_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x009A, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_11_ENTRYID = WoWUnitFields.UNIT_END + 0x009B, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_11_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x009C, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_12_ENTRYID = WoWUnitFields.UNIT_END + 0x009D, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_12_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x009E, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_13_ENTRYID = WoWUnitFields.UNIT_END + 0x009F, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_13_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x00A0, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_14_ENTRYID = WoWUnitFields.UNIT_END + 0x00A1, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_14_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x00A2, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_15_ENTRYID = WoWUnitFields.UNIT_END + 0x00A3, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_15_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x00A4, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_16_ENTRYID = WoWUnitFields.UNIT_END + 0x00A5, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_16_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x00A6, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_17_ENTRYID = WoWUnitFields.UNIT_END + 0x00A7, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_17_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x00A8, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_18_ENTRYID = WoWUnitFields.UNIT_END + 0x00A9, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_18_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x00AA, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_19_ENTRYID = WoWUnitFields.UNIT_END + 0x00AB, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_VISIBLE_ITEM_19_ENCHANTMENT = WoWUnitFields.UNIT_END + 0x00AC, // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
        PLAYER_CHOSEN_TITLE = WoWUnitFields.UNIT_END + 0x00AD, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_FAKE_INEBRIATION = WoWUnitFields.UNIT_END + 0x00AE, // Size: 1, Type: INT, Flags: PUBLIC
        PLAYER_FIELD_PAD_0 = WoWUnitFields.UNIT_END + 0x00AF, // Size: 1, Type: INT, Flags: NONE
        PLAYER_FIELD_INV_SLOT_HEAD = WoWUnitFields.UNIT_END + 0x00B0, // Size: 46, Type: LONG, Flags: PRIVATE
        PLAYER_FIELD_PACK_SLOT_1 = WoWUnitFields.UNIT_END + 0x00DE, // Size: 32, Type: LONG, Flags: PRIVATE
        PLAYER_FIELD_BANK_SLOT_1 = WoWUnitFields.UNIT_END + 0x00FE, // Size: 56, Type: LONG, Flags: PRIVATE
        PLAYER_FIELD_BANKBAG_SLOT_1 = WoWUnitFields.UNIT_END + 0x0136, // Size: 14, Type: LONG, Flags: PRIVATE
        PLAYER_FIELD_VENDORBUYBACK_SLOT_1 = WoWUnitFields.UNIT_END + 0x0144, // Size: 24, Type: LONG, Flags: PRIVATE
        PLAYER_FIELD_KEYRING_SLOT_1 = WoWUnitFields.UNIT_END + 0x015C, // Size: 64, Type: LONG, Flags: PRIVATE
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 = WoWUnitFields.UNIT_END + 0x019C, // Size: 64, Type: LONG, Flags: PRIVATE
        PLAYER_FARSIGHT = WoWUnitFields.UNIT_END + 0x01DC, // Size: 2, Type: LONG, Flags: PRIVATE
        PLAYER__FIELD_KNOWN_TITLES = WoWUnitFields.UNIT_END + 0x01DE, // Size: 2, Type: LONG, Flags: PRIVATE
        PLAYER__FIELD_KNOWN_TITLES1 = WoWUnitFields.UNIT_END + 0x01E0, // Size: 2, Type: LONG, Flags: PRIVATE
        PLAYER__FIELD_KNOWN_TITLES2 = WoWUnitFields.UNIT_END + 0x01E2, // Size: 2, Type: LONG, Flags: PRIVATE
        PLAYER_FIELD_KNOWN_CURRENCIES = WoWUnitFields.UNIT_END + 0x01E4, // Size: 2, Type: LONG, Flags: PRIVATE
        PLAYER_XP = WoWUnitFields.UNIT_END + 0x01E6, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_NEXT_LEVEL_XP = WoWUnitFields.UNIT_END + 0x01E7, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_SKILL_INFO_1_1 = WoWUnitFields.UNIT_END + 0x01E8, // Size: 384, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_CHARACTER_POINTS1 = WoWUnitFields.UNIT_END + 0x0368, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_CHARACTER_POINTS2 = WoWUnitFields.UNIT_END + 0x0369, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_TRACK_CREATURES = WoWUnitFields.UNIT_END + 0x036A, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_TRACK_RESOURCES = WoWUnitFields.UNIT_END + 0x036B, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_BLOCK_PERCENTAGE = WoWUnitFields.UNIT_END + 0x036C, // Size: 1, Type: FLOAT, Flags: PRIVATE
        PLAYER_DODGE_PERCENTAGE = WoWUnitFields.UNIT_END + 0x036D, // Size: 1, Type: FLOAT, Flags: PRIVATE
        PLAYER_PARRY_PERCENTAGE = WoWUnitFields.UNIT_END + 0x036E, // Size: 1, Type: FLOAT, Flags: PRIVATE
        PLAYER_EXPERTISE = WoWUnitFields.UNIT_END + 0x036F, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_OFFHAND_EXPERTISE = WoWUnitFields.UNIT_END + 0x0370, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_CRIT_PERCENTAGE = WoWUnitFields.UNIT_END + 0x0371, // Size: 1, Type: FLOAT, Flags: PRIVATE
        PLAYER_RANGED_CRIT_PERCENTAGE = WoWUnitFields.UNIT_END + 0x0372, // Size: 1, Type: FLOAT, Flags: PRIVATE
        PLAYER_OFFHAND_CRIT_PERCENTAGE = WoWUnitFields.UNIT_END + 0x0373, // Size: 1, Type: FLOAT, Flags: PRIVATE
        PLAYER_SPELL_CRIT_PERCENTAGE1 = WoWUnitFields.UNIT_END + 0x0374, // Size: 7, Type: FLOAT, Flags: PRIVATE
        PLAYER_SHIELD_BLOCK = WoWUnitFields.UNIT_END + 0x037B, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_SHIELD_BLOCK_CRIT_PERCENTAGE = WoWUnitFields.UNIT_END + 0x037C, // Size: 1, Type: FLOAT, Flags: PRIVATE
        PLAYER_EXPLORED_ZONES_1 = WoWUnitFields.UNIT_END + 0x037D, // Size: 128, Type: BYTES, Flags: PRIVATE
        PLAYER_REST_STATE_EXPERIENCE = WoWUnitFields.UNIT_END + 0x03FD, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_COINAGE = WoWUnitFields.UNIT_END + 0x03FE, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_MOD_DAMAGE_DONE_POS = WoWUnitFields.UNIT_END + 0x03FF, // Size: 7, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_MOD_DAMAGE_DONE_NEG = WoWUnitFields.UNIT_END + 0x0406, // Size: 7, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_MOD_DAMAGE_DONE_PCT = WoWUnitFields.UNIT_END + 0x040D, // Size: 7, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_MOD_HEALING_DONE_POS = WoWUnitFields.UNIT_END + 0x0414, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_MOD_HEALING_PCT = WoWUnitFields.UNIT_END + 0x0415, // Size: 1, Type: FLOAT, Flags: PRIVATE
        PLAYER_FIELD_MOD_HEALING_DONE_PCT = WoWUnitFields.UNIT_END + 0x0416, // Size: 1, Type: FLOAT, Flags: PRIVATE
        PLAYER_FIELD_MOD_TARGET_RESISTANCE = WoWUnitFields.UNIT_END + 0x0417, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE = WoWUnitFields.UNIT_END + 0x0418, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_BYTES = WoWUnitFields.UNIT_END + 0x0419, // Size: 1, Type: BYTES, Flags: PRIVATE
        PLAYER_AMMO_ID = WoWUnitFields.UNIT_END + 0x041A, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_SELF_RES_SPELL = WoWUnitFields.UNIT_END + 0x041B, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_PVP_MEDALS = WoWUnitFields.UNIT_END + 0x041C, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_BUYBACK_PRICE_1 = WoWUnitFields.UNIT_END + 0x041D, // Size: 12, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_BUYBACK_TIMESTAMP_1 = WoWUnitFields.UNIT_END + 0x0429, // Size: 12, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_KILLS = WoWUnitFields.UNIT_END + 0x0435, // Size: 1, Type: TWO_SHORT, Flags: PRIVATE
        PLAYER_FIELD_TODAY_CONTRIBUTION = WoWUnitFields.UNIT_END + 0x0436, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_YESTERDAY_CONTRIBUTION = WoWUnitFields.UNIT_END + 0x0437, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_LIFETIME_HONORBALE_KILLS = WoWUnitFields.UNIT_END + 0x0438, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_BYTES2 = WoWUnitFields.UNIT_END + 0x0439, // Size: 1, Type: 6, Flags: PRIVATE
        PLAYER_FIELD_WATCHED_FACTION_INDEX = WoWUnitFields.UNIT_END + 0x043A, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_COMBAT_RATING_1 = WoWUnitFields.UNIT_END + 0x043B, // Size: 25, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_ARENA_TEAM_INFO_1_1 = WoWUnitFields.UNIT_END + 0x0454, // Size: 21, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_HONOR_CURRENCY = WoWUnitFields.UNIT_END + 0x0469, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_ARENA_CURRENCY = WoWUnitFields.UNIT_END + 0x046A, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_MAX_LEVEL = WoWUnitFields.UNIT_END + 0x046B, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_DAILY_QUESTS_1 = WoWUnitFields.UNIT_END + 0x046C, // Size: 25, Type: INT, Flags: PRIVATE
        PLAYER_RUNE_REGEN_1 = WoWUnitFields.UNIT_END + 0x0485, // Size: 4, Type: FLOAT, Flags: PRIVATE
        PLAYER_NO_REAGENT_COST_1 = WoWUnitFields.UNIT_END + 0x0489, // Size: 3, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_GLYPH_SLOTS_1 = WoWUnitFields.UNIT_END + 0x048C, // Size: 6, Type: INT, Flags: PRIVATE
        PLAYER_FIELD_GLYPHS_1 = WoWUnitFields.UNIT_END + 0x0492, // Size: 6, Type: INT, Flags: PRIVATE
        PLAYER_GLYPHS_ENABLED = WoWUnitFields.UNIT_END + 0x0498, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_PET_SPELL_POWER = WoWUnitFields.UNIT_END + 0x0499, // Size: 1, Type: INT, Flags: PRIVATE
        PLAYER_END = WoWUnitFields.UNIT_END + 0x049A,

        /*/
        PLAYER__FIELD_KNOWN_TITLES = 0x272,
        PLAYER__FIELD_KNOWN_TITLES1 = 0x274,
        PLAYER__FIELD_KNOWN_TITLES2 = 630,
        PLAYER_AMMO_ID = 0x4ae,
        PLAYER_BLOCK_PERCENTAGE = 0x400,
        PLAYER_BYTES = 0x99,
        PLAYER_BYTES_2 = 0x9a,
        PLAYER_BYTES_3 = 0x9b,
        PLAYER_CHARACTER_POINTS1 = 0x3fc,
        PLAYER_CHARACTER_POINTS2 = 0x3fd,
        PLAYER_CHOSEN_TITLE = 0x141,
        PLAYER_CRIT_PERCENTAGE = 0x405,
        PLAYER_DODGE_PERCENTAGE = 0x401,
        PLAYER_DUEL_ARBITER = 0x94,
        PLAYER_DUEL_TEAM = 0x9c,
        PLAYER_EXPERTISE = 0x403,
        PLAYER_EXPLORED_ZONES_1 = 0x411,
        PLAYER_FAKE_INEBRIATION = 0x142,
        PLAYER_FARSIGHT = 0x270,
        PLAYER_FIELD_ARENA_CURRENCY = 0x4fe,
        PLAYER_FIELD_ARENA_TEAM_INFO_1_1 = 0x4e8,
        PLAYER_FIELD_BANK_SLOT_1 = 0x192,
        PLAYER_FIELD_BANKBAG_SLOT_1 = 0x1ca,
        PLAYER_FIELD_BUYBACK_PRICE_1 = 0x4b1,
        PLAYER_FIELD_BUYBACK_TIMESTAMP_1 = 0x4bd,
        PLAYER_FIELD_BYTES = 0x4ad,
        PLAYER_FIELD_BYTES2 = 0x4cd,
        PLAYER_FIELD_COINAGE = 0x492,
        PLAYER_FIELD_COMBAT_RATING_1 = 0x4cf,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 = 560,
        PLAYER_FIELD_DAILY_QUESTS_1 = 0x500,
        PLAYER_FIELD_GLYPH_SLOTS_1 = 0x520,
        PLAYER_FIELD_GLYPHS_1 = 0x526,
        PLAYER_FIELD_HONOR_CURRENCY = 0x4fd,
        PLAYER_FIELD_INV_SLOT_HEAD = 0x144,
        PLAYER_FIELD_KEYRING_SLOT_1 = 0x1f0,
        PLAYER_FIELD_KILLS = 0x4c9,
        PLAYER_FIELD_KNOWN_CURRENCIES = 0x278,
        PLAYER_FIELD_LIFETIME_HONORBALE_KILLS = 0x4cc,
        PLAYER_FIELD_MAX_LEVEL = 0x4ff,
        PLAYER_FIELD_MOD_DAMAGE_DONE_NEG = 0x49a,
        PLAYER_FIELD_MOD_DAMAGE_DONE_PCT = 0x4a1,
        PLAYER_FIELD_MOD_DAMAGE_DONE_POS = 0x493,
        PLAYER_FIELD_MOD_HEALING_DONE_PCT = 0x4aa,
        PLAYER_FIELD_MOD_HEALING_DONE_POS = 0x4a8,
        PLAYER_FIELD_MOD_HEALING_PCT = 0x4a9,
        PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE = 0x4ac,
        PLAYER_FIELD_MOD_TARGET_RESISTANCE = 0x4ab,
        PLAYER_FIELD_PACK_SLOT_1 = 370,
        PLAYER_FIELD_PAD_0 = 0x143,
        PLAYER_FIELD_PVP_MEDALS = 0x4b0,
        PLAYER_FIELD_TODAY_CONTRIBUTION = 0x4ca,
        PLAYER_FIELD_VENDORBUYBACK_SLOT_1 = 0x1d8,
        PLAYER_FIELD_WATCHED_FACTION_INDEX = 0x4ce,
        PLAYER_FIELD_YESTERDAY_CONTRIBUTION = 0x4cb,
        PLAYER_FLAGS = 150,
        PLAYER_GLYPHS_ENABLED = 0x52c,
        PLAYER_GUILD_TIMESTAMP = 0x9d,
        PLAYER_GUILDID = 0x97,
        PLAYER_GUILDRANK = 0x98,
        PLAYER_NEXT_LEVEL_XP = 0x27b,
        PLAYER_NO_REAGENT_COST_1 = 0x51d,
        PLAYER_OFFHAND_CRIT_PERCENTAGE = 0x407,
        PLAYER_OFFHAND_EXPERTISE = 0x404,
        PLAYER_PARRY_PERCENTAGE = 0x402,
        PLAYER_PET_SPELL_POWER = 0x52d,
        PLAYER_QUEST_LOG_1_1 = 0x9e,
        PLAYER_QUEST_LOG_1_2 = 0x9f,
        PLAYER_QUEST_LOG_1_3 = 160,
        PLAYER_QUEST_LOG_1_4 = 0xa2,
        PLAYER_QUEST_LOG_10_1 = 0xcb,
        PLAYER_QUEST_LOG_10_2 = 0xcc,
        PLAYER_QUEST_LOG_10_3 = 0xcd,
        PLAYER_QUEST_LOG_10_5 = 0xcf,
        PLAYER_QUEST_LOG_11_1 = 0xd0,
        PLAYER_QUEST_LOG_11_2 = 0xd1,
        PLAYER_QUEST_LOG_11_3 = 210,
        PLAYER_QUEST_LOG_11_5 = 0xd4,
        PLAYER_QUEST_LOG_12_1 = 0xd5,
        PLAYER_QUEST_LOG_12_2 = 0xd6,
        PLAYER_QUEST_LOG_12_3 = 0xd7,
        PLAYER_QUEST_LOG_12_5 = 0xd9,
        PLAYER_QUEST_LOG_13_1 = 0xda,
        PLAYER_QUEST_LOG_13_2 = 0xdb,
        PLAYER_QUEST_LOG_13_3 = 220,
        PLAYER_QUEST_LOG_13_5 = 0xde,
        PLAYER_QUEST_LOG_14_1 = 0xdf,
        PLAYER_QUEST_LOG_14_2 = 0xe0,
        PLAYER_QUEST_LOG_14_3 = 0xe1,
        PLAYER_QUEST_LOG_14_5 = 0xe3,
        PLAYER_QUEST_LOG_15_1 = 0xe4,
        PLAYER_QUEST_LOG_15_2 = 0xe5,
        PLAYER_QUEST_LOG_15_3 = 230,
        PLAYER_QUEST_LOG_15_5 = 0xe8,
        PLAYER_QUEST_LOG_16_1 = 0xe9,
        PLAYER_QUEST_LOG_16_2 = 0xea,
        PLAYER_QUEST_LOG_16_3 = 0xeb,
        PLAYER_QUEST_LOG_16_5 = 0xed,
        PLAYER_QUEST_LOG_17_1 = 0xee,
        PLAYER_QUEST_LOG_17_2 = 0xef,
        PLAYER_QUEST_LOG_17_3 = 240,
        PLAYER_QUEST_LOG_17_5 = 0xf2,
        PLAYER_QUEST_LOG_18_1 = 0xf3,
        PLAYER_QUEST_LOG_18_2 = 0xf4,
        PLAYER_QUEST_LOG_18_3 = 0xf5,
        PLAYER_QUEST_LOG_18_5 = 0xf7,
        PLAYER_QUEST_LOG_19_1 = 0xf8,
        PLAYER_QUEST_LOG_19_2 = 0xf9,
        PLAYER_QUEST_LOG_19_3 = 250,
        PLAYER_QUEST_LOG_19_5 = 0xfc,
        PLAYER_QUEST_LOG_2_1 = 0xa3,
        PLAYER_QUEST_LOG_2_2 = 0xa4,
        PLAYER_QUEST_LOG_2_3 = 0xa5,
        PLAYER_QUEST_LOG_2_5 = 0xa7,
        PLAYER_QUEST_LOG_20_1 = 0xfd,
        PLAYER_QUEST_LOG_20_2 = 0xfe,
        PLAYER_QUEST_LOG_20_3 = 0xff,
        PLAYER_QUEST_LOG_20_5 = 0x101,
        PLAYER_QUEST_LOG_21_1 = 0x102,
        PLAYER_QUEST_LOG_21_2 = 0x103,
        PLAYER_QUEST_LOG_21_3 = 260,
        PLAYER_QUEST_LOG_21_5 = 0x106,
        PLAYER_QUEST_LOG_22_1 = 0x107,
        PLAYER_QUEST_LOG_22_2 = 0x108,
        PLAYER_QUEST_LOG_22_3 = 0x109,
        PLAYER_QUEST_LOG_22_5 = 0x10b,
        PLAYER_QUEST_LOG_23_1 = 0x10c,
        PLAYER_QUEST_LOG_23_2 = 0x10d,
        PLAYER_QUEST_LOG_23_3 = 270,
        PLAYER_QUEST_LOG_23_5 = 0x110,
        PLAYER_QUEST_LOG_24_1 = 0x111,
        PLAYER_QUEST_LOG_24_2 = 0x112,
        PLAYER_QUEST_LOG_24_3 = 0x113,
        PLAYER_QUEST_LOG_24_5 = 0x115,
        PLAYER_QUEST_LOG_25_1 = 0x116,
        PLAYER_QUEST_LOG_25_2 = 0x117,
        PLAYER_QUEST_LOG_25_3 = 280,
        PLAYER_QUEST_LOG_25_5 = 0x11a,
        PLAYER_QUEST_LOG_3_1 = 0xa8,
        PLAYER_QUEST_LOG_3_2 = 0xa9,
        PLAYER_QUEST_LOG_3_3 = 170,
        PLAYER_QUEST_LOG_3_5 = 0xac,
        PLAYER_QUEST_LOG_4_1 = 0xad,
        PLAYER_QUEST_LOG_4_2 = 0xae,
        PLAYER_QUEST_LOG_4_3 = 0xaf,
        PLAYER_QUEST_LOG_4_5 = 0xb1,
        PLAYER_QUEST_LOG_5_1 = 0xb2,
        PLAYER_QUEST_LOG_5_2 = 0xb3,
        PLAYER_QUEST_LOG_5_3 = 180,
        PLAYER_QUEST_LOG_5_5 = 0xb6,
        PLAYER_QUEST_LOG_6_1 = 0xb7,
        PLAYER_QUEST_LOG_6_2 = 0xb8,
        PLAYER_QUEST_LOG_6_3 = 0xb9,
        PLAYER_QUEST_LOG_6_5 = 0xbb,
        PLAYER_QUEST_LOG_7_1 = 0xbc,
        PLAYER_QUEST_LOG_7_2 = 0xbd,
        PLAYER_QUEST_LOG_7_3 = 190,
        PLAYER_QUEST_LOG_7_5 = 0xc0,
        PLAYER_QUEST_LOG_8_1 = 0xc1,
        PLAYER_QUEST_LOG_8_2 = 0xc2,
        PLAYER_QUEST_LOG_8_3 = 0xc3,
        PLAYER_QUEST_LOG_8_5 = 0xc5,
        PLAYER_QUEST_LOG_9_1 = 0xc6,
        PLAYER_QUEST_LOG_9_2 = 0xc7,
        PLAYER_QUEST_LOG_9_3 = 200,
        PLAYER_QUEST_LOG_9_5 = 0xca,
        PLAYER_RANGED_CRIT_PERCENTAGE = 0x406,
        PLAYER_REST_STATE_EXPERIENCE = 0x491,
        PLAYER_RUNE_REGEN_1 = 0x519,
        PLAYER_SELF_RES_SPELL = 0x4af,
        PLAYER_SHIELD_BLOCK = 0x40f,
        PLAYER_SHIELD_BLOCK_CRIT_PERCENTAGE = 0x410,
        PLAYER_SKILL_INFO_1_1 = 0x27c,
        PLAYER_SPELL_CRIT_PERCENTAGE1 = 0x408,
        PLAYER_TRACK_CREATURES = 0x3fe,
        PLAYER_TRACK_RESOURCES = 0x3ff,
        PLAYER_VISIBLE_ITEM_1_ENCHANTMENT = 0x11c,
        PLAYER_VISIBLE_ITEM_1_ENTRYID = 0x11b,
        PLAYER_VISIBLE_ITEM_10_ENCHANTMENT = 0x12e,
        PLAYER_VISIBLE_ITEM_10_ENTRYID = 0x12d,
        PLAYER_VISIBLE_ITEM_11_ENCHANTMENT = 0x130,
        PLAYER_VISIBLE_ITEM_11_ENTRYID = 0x12f,
        PLAYER_VISIBLE_ITEM_12_ENCHANTMENT = 0x132,
        PLAYER_VISIBLE_ITEM_12_ENTRYID = 0x131,
        PLAYER_VISIBLE_ITEM_13_ENCHANTMENT = 0x134,
        PLAYER_VISIBLE_ITEM_13_ENTRYID = 0x133,
        PLAYER_VISIBLE_ITEM_14_ENCHANTMENT = 310,
        PLAYER_VISIBLE_ITEM_14_ENTRYID = 0x135,
        PLAYER_VISIBLE_ITEM_15_ENCHANTMENT = 0x138,
        PLAYER_VISIBLE_ITEM_15_ENTRYID = 0x137,
        PLAYER_VISIBLE_ITEM_16_ENCHANTMENT = 0x13a,
        PLAYER_VISIBLE_ITEM_16_ENTRYID = 0x139,
        PLAYER_VISIBLE_ITEM_17_ENCHANTMENT = 0x13c,
        PLAYER_VISIBLE_ITEM_17_ENTRYID = 0x13b,
        PLAYER_VISIBLE_ITEM_18_ENCHANTMENT = 0x13e,
        PLAYER_VISIBLE_ITEM_18_ENTRYID = 0x13d,
        PLAYER_VISIBLE_ITEM_19_ENCHANTMENT = 320,
        PLAYER_VISIBLE_ITEM_19_ENTRYID = 0x13f,
        PLAYER_VISIBLE_ITEM_2_ENCHANTMENT = 0x11e,
        PLAYER_VISIBLE_ITEM_2_ENTRYID = 0x11d,
        PLAYER_VISIBLE_ITEM_3_ENCHANTMENT = 0x120,
        PLAYER_VISIBLE_ITEM_3_ENTRYID = 0x11f,
        PLAYER_VISIBLE_ITEM_4_ENCHANTMENT = 290,
        PLAYER_VISIBLE_ITEM_4_ENTRYID = 0x121,
        PLAYER_VISIBLE_ITEM_5_ENCHANTMENT = 0x124,
        PLAYER_VISIBLE_ITEM_5_ENTRYID = 0x123,
        PLAYER_VISIBLE_ITEM_6_ENCHANTMENT = 0x126,
        PLAYER_VISIBLE_ITEM_6_ENTRYID = 0x125,
        PLAYER_VISIBLE_ITEM_7_ENCHANTMENT = 0x128,
        PLAYER_VISIBLE_ITEM_7_ENTRYID = 0x127,
        PLAYER_VISIBLE_ITEM_8_ENCHANTMENT = 0x12a,
        PLAYER_VISIBLE_ITEM_8_ENTRYID = 0x129,
        PLAYER_VISIBLE_ITEM_9_ENCHANTMENT = 300,
        PLAYER_VISIBLE_ITEM_9_ENTRYID = 0x12b,
        PLAYER_XP = 0x27a,

        PLAYER_END = WoWUnitFields.UNIT_END + 0x049A,
        /*/
    };

    public enum WoWGameObjectFields
    {
        OBJECT_FIELD_CREATED_BY = WoWObjectFields.OBJECT_END + 0x0000, // Size: 2, Type: LONG, Flags: PUBLIC
        GAMEOBJECT_DISPLAYID = WoWObjectFields.OBJECT_END + 0x0002, // Size: 1, Type: INT, Flags: PUBLIC
        GAMEOBJECT_FLAGS = WoWObjectFields.OBJECT_END + 0x0003, // Size: 1, Type: INT, Flags: PUBLIC
        GAMEOBJECT_PARENTROTATION = WoWObjectFields.OBJECT_END + 0x0004, // Size: 4, Type: FLOAT, Flags: PUBLIC
        GAMEOBJECT_DYNAMIC = WoWObjectFields.OBJECT_END + 0x0008, // Size: 1, Type: TWO_SHORT, Flags: DYNAMIC
        GAMEOBJECT_FACTION = WoWObjectFields.OBJECT_END + 0x0009, // Size: 1, Type: INT, Flags: PUBLIC
        GAMEOBJECT_LEVEL = WoWObjectFields.OBJECT_END + 0x000A, // Size: 1, Type: INT, Flags: PUBLIC
        GAMEOBJECT_BYTES_1 = WoWObjectFields.OBJECT_END + 0x000B, // Size: 1, Type: BYTES, Flags: PUBLIC
        GAMEOBJECT_END = WoWObjectFields.OBJECT_END + 0x000C,
    };

    public enum WoWDynamicObjectFields
    {
        DYNAMICOBJECT_CASTER = WoWObjectFields.OBJECT_END + 0x0000, // Size: 2, Type: LONG, Flags: PUBLIC
        DYNAMICOBJECT_BYTES = WoWObjectFields.OBJECT_END + 0x0002, // Size: 1, Type: BYTES, Flags: PUBLIC
        DYNAMICOBJECT_SPELLID = WoWObjectFields.OBJECT_END + 0x0003, // Size: 1, Type: INT, Flags: PUBLIC
        DYNAMICOBJECT_RADIUS = WoWObjectFields.OBJECT_END + 0x0004, // Size: 1, Type: FLOAT, Flags: PUBLIC
        DYNAMICOBJECT_CASTTIME = WoWObjectFields.OBJECT_END + 0x0005, // Size: 1, Type: INT, Flags: PUBLIC
        DYNAMICOBJECT_END = WoWObjectFields.OBJECT_END + 0x0006,
    };

    public enum WoWCorpseFields
    {
        CORPSE_FIELD_OWNER = WoWObjectFields.OBJECT_END + 0x0000, // Size: 2, Type: LONG, Flags: PUBLIC
        CORPSE_FIELD_PARTY = WoWObjectFields.OBJECT_END + 0x0002, // Size: 2, Type: LONG, Flags: PUBLIC
        CORPSE_FIELD_DISPLAY_ID = WoWObjectFields.OBJECT_END + 0x0004, // Size: 1, Type: INT, Flags: PUBLIC
        CORPSE_FIELD_ITEM = WoWObjectFields.OBJECT_END + 0x0005, // Size: 19, Type: INT, Flags: PUBLIC
        CORPSE_FIELD_BYTES_1 = WoWObjectFields.OBJECT_END + 0x0018, // Size: 1, Type: BYTES, Flags: PUBLIC
        CORPSE_FIELD_BYTES_2 = WoWObjectFields.OBJECT_END + 0x0019, // Size: 1, Type: BYTES, Flags: PUBLIC
        CORPSE_FIELD_GUILD = WoWObjectFields.OBJECT_END + 0x001A, // Size: 1, Type: INT, Flags: PUBLIC
        CORPSE_FIELD_FLAGS = WoWObjectFields.OBJECT_END + 0x001B, // Size: 1, Type: INT, Flags: PUBLIC
        CORPSE_FIELD_DYNAMIC_FLAGS = WoWObjectFields.OBJECT_END + 0x001C, // Size: 1, Type: INT, Flags: DYNAMIC
        CORPSE_FIELD_PAD = WoWObjectFields.OBJECT_END + 0x001D, // Size: 1, Type: INT, Flags: NONE
        CORPSE_END = WoWObjectFields.OBJECT_END + 0x001E,
    };
}